site_name: Beremiz Documentation
site_url: https://adaiasmagdiel.github.io/Beremiz

repo_url: https://github.com/AdaiasMagdiel/Beremiz
repo_name: AdaiasMagdiel/Beremiz

nav:
  - Home: index.md
  - Comments: comments.md
  - Control Structures: control-structures.md
  - Conditional Execution: conditional-execution.md
  - Stack Operations: stack-operations.md
  - Displaying Data: displaying-data.md
  - Arithmetic and Comparison Operations: arithmetic-comparison.md
  - Defining Constants and Functions: constants-functions.md
  - Including Files: including.md
  - Modules and Methods:
      - String Module: modules/string-module.md
      - Math Module: modules/math-module.md
  - Language Reference: reference.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - git-committers:
      repository: AdaiasMagdiel/Beremiz
      branch: main

theme:
  favicon: images/favicon.png
  
  name: material

  features:
    - content.code.copy

  icon:
    logo: octicons/stack-16
    repo: fontawesome/brands/github

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: teal
      accent: deep purple
